---

influxdb:
  build: ../../docker/influxdb
  volumes:
    - ./influxdb.toml:/influxdb.toml
  hostname: influxdb
  ports:
    - 8083:8083
    - 8086:8086

telegraf:
  build: ../../docker/telegraf
  volumes:
    - ./telegraf.toml:/telegraf.toml
  hostname: telegraf
  links:
    - influxdb

chronograf:
  build: ../../docker/chronograf
  volumes:
    - ./chronograf.toml:/chronograf.toml
  ports:
    - 10000:10000
  links:
    - influxdb


#kapacitor:
#  build: ../../docker/kapacitor
