---

influxdb:
  build: ../../docker/influxdb
  volumes:
    - ./influxdb.toml:/influxdb.toml
  hostname: influxdb
  restart: always
  ports:
    - 8083:8083
    - 8086:8086

telegraf:
  build: ../../docker/telegraf
  volumes:
    - ./telegraf.toml:/telegraf.toml
  hostname: telegraf
  restart: always
  links:
    - influxdb

chronograf:
  build: ../../docker/chronograf
  volumes:
    - ./chronograf.toml:/chronograf.toml
  ports:
    - 10000:10000
  hostname: chronograf
  restart: always
  links:
    - influxdb


kapacitor:
  build: ../../docker/kapacitor
  restart: always  # if influxdb isn't ready, it will exit instead of retry. dumb
  volumes:
    - ./kapacitor.toml:/kapacitor.toml
  ports:
    - 9092:9092
  links:
    - influxdb
  hostname: kapacitor
