---

influxdb:
  build: ../../docker/influxdb
  volumes:
    - ./influxdb.toml:/influxdb.toml
  hostname: tick-sc-influxdb
  container_name: tick-sc-influxdb
  restart: always
  ports:
    - 8083:8083
    - 8086:8086
  log_driver: "json-file"
  log_opt:
    max-size: "100k"
    max-file: "2"

telegraf:
  build: telegraf/
  volumes:
    - ./telegraf.toml:/telegraf.toml
  hostname: tick-sc-telegraf
  container_name: tick-sc-telegraf
  restart: always
  links:
    - influxdb
    - nginx
    - apache
  log_driver: "json-file"
  log_opt:
    max-size: "100k"
    max-file: "2"

chronograf:
  build: ../../docker/chronograf
  volumes:
    - ./chronograf.toml:/chronograf.toml
  ports:
    - 10000:10000
  hostname: tick-sc-chronograf
  container_name: tick-sc-chronograf
  restart: always
  links:
    - influxdb
  log_driver: "json-file"
  log_opt:
    max-size: "100k"
    max-file: "2"


kapacitor:
  build: ../../docker/kapacitor
  restart: always  # if influxdb isn't ready, it will exit instead of retry. dumb
  hostname: tick-sc-kapacitor
  container_name: tick-sc-kapacitor
  volumes:
    - ./kapacitor.toml:/kapacitor.toml
    - ./kapacitor-data:/kapacitor-data
  ports:
    - 9092:9092
  links:
    - influxdb
  log_driver: "json-file"
  log_opt:
    max-size: "100k"
    max-file: "2"

nginx:
  image: nginx
  hostname: tick-sc-nginx
  container_name: tick-sc-nginx
  log_driver: "json-file"
  log_opt:
    max-size: "100k"
    max-file: "2"


apache:
  image: httpd
  hostname: tick-sc-apache
  container_name: tick-sc-apache
  log_driver: "json-file"
  log_opt:
    max-size: "100k"
    max-file: "2"
